[package]
name = "yaz0_rust"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
yaz0 = { version = "0.3.0" }
