[package]
name = "yaz0rust"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaz0 = "0.3.0"
indicatif = "0.16.2"
thread-control = { git = "https://github.com/DenisKolodin/thread-control" }