name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-Win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        pushd ${{ github.workspace }}
        cargo build --release
        cd target
        cd release
        mv yaz0rust.exe ${{ github.workspace }}
        popd
        ls
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: yaz0rust.exe
